<a href="https://colab.research.google.com/github/Anisha2810/Neural-networks-and-deep-learning/blob/main/exp_1_nd_2_neural_networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install torch

In [ ]:
import torch

# 1. Scalar (0D Tensor)
scalar = torch.tensor(5)
print("Scalar (0D Tensor):", scalar)
print("Shape:", scalar.shape)
print()

# 2. Vector (1D Tensor)
vector = torch.tensor([1, 2, 3, 4])
print("Vector (1D Tensor):", vector)
print("Shape:", vector.shape)
print()

# 3. Matrix (2D Tensor)
matrix = torch.tensor([[1, 2], [3, 4]])
print("Matrix (2D Tensor):")
print(matrix)
print("Shape:", matrix.shape)
print()

# 4. 3D Tensor
tensor_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3D Tensor:")
print(tensor_3d)
print("Shape:", tensor_3d.shape)
print()

# 5. Random Tensor
random_tensor = torch.rand(3, 3)
print("Random Tensor:")
print(random_tensor)
print()

# 6. Zero Tensor
zero_tensor = torch.zeros(2, 3)
print("Zero Tensor:")
print(zero_tensor)
print()

# 7. Ones Tensor
ones_tensor = torch.ones(2, 3)
print("Ones Tensor:")
print(ones_tensor)
print()

# 8. Tensor with Specific Data Type
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

print("Float Tensor:", float_tensor)
print("Integer Tensor:", int_tensor)
print()

# 9. Tensor Operations
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)

Scalar (0D Tensor): tensor(5)
Shape: torch.Size([])

Vector (1D Tensor): tensor([1, 2, 3, 4])
Shape: torch.Size([4])

Matrix (2D Tensor):
tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2])

3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])

Random Tensor:
tensor([[0.1347, 0.1681, 0.7500],
        [0.9781, 0.2515, 0.5011],
        [0.2775, 0.0025, 0.9391]])

Zero Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Float Tensor: tensor([1., 2., 3.])
Integer Tensor: tensor([1, 2, 3], dtype=torch.int32)

Addition: tensor([5, 7, 9])
Multiplication: tensor([ 4, 10, 18])


In [ ]:
# Import NumPy library for vector operations
import numpy as np

# Create two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Display the vectors
print("Vector A:", vector_a)
print("Vector B:", vector_b)
print()

# 1. Vector Addition
# Adds corresponding elements of both vectors
addition = vector_a + vector_b
print("Addition (A + B):", addition)

# 2. Vector Subtraction
# Subtracts corresponding elements
subtraction = vector_a - vector_b
print("Subtraction (A - B):", subtraction)

# 3. Scalar Multiplication
# Multiply each element of vector by a scalar value
scalar_multiplication = 3 * vector_a
print("Scalar Multiplication (3 * A):", scalar_multiplication)

# 4. Dot Product
# Multiply corresponding elements and sum them
dot_product = np.dot(vector_a, vector_b)
print("Dot Product (A . B):", dot_product)

# 5. Magnitude (Length) of Vector
# sqrt(x^2 + y^2 + z^2)
magnitude_a = np.linalg.norm(vector_a)
print("Magnitude of Vector A:", magnitude_a)

# 6. Unit Vector
# Divide vector by its magnitude
unit_vector_a = vector_a / magnitude_a
print("Unit Vector of A:", unit_vector_a)

# 7. Element-wise Multiplication
# Multiply elements at same positions
elementwise = vector_a * vector_b
print("Element-wise Multiplication:", elementwise)

Vector A: [1 2 3]
Vector B: [4 5 6]

Addition (A + B): [5 7 9]
Subtraction (A - B): [-3 -3 -3]
Scalar Multiplication (3 * A): [3 6 9]
Dot Product (A . B): 32
Magnitude of Vector A: 3.7416573867739413
Unit Vector of A: [0.26726124 0.53452248 0.80178373]
Element-wise Multiplication: [ 4 10 18]
